<?php
/**
 * @file
 * Code for the Fial Core feature.
 */

/**
 * Include additional files.
 */
$dirname = dirname(__FILE__) . '/includes';
$includes = file_scan_directory($dirname, '/.inc$/');
foreach (module_list() as $module) {
  $file = "{$dirname}/{$module}.inc";
  if (isset($includes[$file])) {
    require_once $file;
  }
}

/**
 * Features include.
 */
include_once 'fial_core.features.inc';

/**
 * Implements hook_preprocess_page().
 */
function fial_core_preprocess_page(&$vars) {
  global $theme;

  if (variable_get('admin_theme', 'seven') == $theme) {
    drupal_add_css(drupal_get_path('theme', 'fial_theme') . '/css/fial.admin.css');
  }
}
