<?php

/**
 * Implements hook_boot()
 */
function fial_wording_boot() {
  global $conf;
  $conf['locale_custom_strings_en'][''] = _fial_wording_strings();
}

function _fial_wording_strings() {
  return array(
    //'--Original' => '--Translated',
    'My Topics' => 'My Forums',
    'My Hubs' => 'My Groups',
    '<h2>Hubs You Hosted</h2> !groups_hosted <h2>Hubs You Joined</h2> !groups_joined' => '<h2>Groups You Hosted</h2> !groups_hosted <h2>Groups You Joined</h2> !groups_joined'
  );
}